# Generated by Django 5.0.6 on 2024-07-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(default='General', max_length=255)),
                ('description', models.TextField()),
                ('favourite', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
